name: Rent591Watcher

on:
  schedule:
  # scheduled at 8, 13, 19 (UTC+8), weekdays
    - cron: "0 8,13,19 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.10'
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run Python Code
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
          URL: ${{ secrets.URL }}
        run: python main.py
